// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: captcha.proto

#include "captcha.pb.h"
#include "captcha.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace captcha {

static const char* CaptchaService_method_names[] = {
  "/captcha.CaptchaService/Ping",
  "/captcha.CaptchaService/GetSlide",
  "/captcha.CaptchaService/VerifySlide",
  "/captcha.CaptchaService/GetRotate",
  "/captcha.CaptchaService/VerifyRotate",
};

std::unique_ptr< CaptchaService::Stub> CaptchaService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CaptchaService::Stub> stub(new CaptchaService::Stub(channel, options));
  return stub;
}

CaptchaService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(CaptchaService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSlide_(CaptchaService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VerifySlide_(CaptchaService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRotate_(CaptchaService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VerifyRotate_(CaptchaService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CaptchaService::Stub::Ping(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::captcha::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::captcha::PingRequest, ::captcha::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void CaptchaService::Stub::async::Ping(::grpc::ClientContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::captcha::PingRequest, ::captcha::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void CaptchaService::Stub::async::Ping(::grpc::ClientContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>* CaptchaService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::captcha::PingResponse, ::captcha::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>* CaptchaService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CaptchaService::Stub::GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::captcha::GetSlideResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::captcha::GetSlideRequest, ::captcha::GetSlideResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSlide_, context, request, response);
}

void CaptchaService::Stub::async::GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::captcha::GetSlideRequest, ::captcha::GetSlideResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSlide_, context, request, response, std::move(f));
}

void CaptchaService::Stub::async::GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSlide_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>* CaptchaService::Stub::PrepareAsyncGetSlideRaw(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::captcha::GetSlideResponse, ::captcha::GetSlideRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSlide_, context, request);
}

::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>* CaptchaService::Stub::AsyncGetSlideRaw(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSlideRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CaptchaService::Stub::VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::captcha::VerifySlideResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VerifySlide_, context, request, response);
}

void CaptchaService::Stub::async::VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifySlide_, context, request, response, std::move(f));
}

void CaptchaService::Stub::async::VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifySlide_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>* CaptchaService::Stub::PrepareAsyncVerifySlideRaw(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::captcha::VerifySlideResponse, ::captcha::VerifySlideRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifySlide_, context, request);
}

::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>* CaptchaService::Stub::AsyncVerifySlideRaw(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVerifySlideRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CaptchaService::Stub::GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::captcha::GetRotateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::captcha::GetRotateRequest, ::captcha::GetRotateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRotate_, context, request, response);
}

void CaptchaService::Stub::async::GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::captcha::GetRotateRequest, ::captcha::GetRotateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRotate_, context, request, response, std::move(f));
}

void CaptchaService::Stub::async::GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRotate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>* CaptchaService::Stub::PrepareAsyncGetRotateRaw(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::captcha::GetRotateResponse, ::captcha::GetRotateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRotate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>* CaptchaService::Stub::AsyncGetRotateRaw(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRotateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CaptchaService::Stub::VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::captcha::VerifyRotateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VerifyRotate_, context, request, response);
}

void CaptchaService::Stub::async::VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyRotate_, context, request, response, std::move(f));
}

void CaptchaService::Stub::async::VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyRotate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>* CaptchaService::Stub::PrepareAsyncVerifyRotateRaw(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::captcha::VerifyRotateResponse, ::captcha::VerifyRotateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifyRotate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>* CaptchaService::Stub::AsyncVerifyRotateRaw(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVerifyRotateRaw(context, request, cq);
  result->StartCall();
  return result;
}

CaptchaService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CaptchaService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CaptchaService::Service, ::captcha::PingRequest, ::captcha::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CaptchaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::captcha::PingRequest* req,
             ::captcha::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CaptchaService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CaptchaService::Service, ::captcha::GetSlideRequest, ::captcha::GetSlideResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CaptchaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::captcha::GetSlideRequest* req,
             ::captcha::GetSlideResponse* resp) {
               return service->GetSlide(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CaptchaService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CaptchaService::Service, ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CaptchaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::captcha::VerifySlideRequest* req,
             ::captcha::VerifySlideResponse* resp) {
               return service->VerifySlide(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CaptchaService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CaptchaService::Service, ::captcha::GetRotateRequest, ::captcha::GetRotateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CaptchaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::captcha::GetRotateRequest* req,
             ::captcha::GetRotateResponse* resp) {
               return service->GetRotate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CaptchaService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CaptchaService::Service, ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CaptchaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::captcha::VerifyRotateRequest* req,
             ::captcha::VerifyRotateResponse* resp) {
               return service->VerifyRotate(ctx, req, resp);
             }, this)));
}

CaptchaService::Service::~Service() {
}

::grpc::Status CaptchaService::Service::Ping(::grpc::ServerContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CaptchaService::Service::GetSlide(::grpc::ServerContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CaptchaService::Service::VerifySlide(::grpc::ServerContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CaptchaService::Service::GetRotate(::grpc::ServerContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CaptchaService::Service::VerifyRotate(::grpc::ServerContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace captcha

