// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: captcha.proto
#ifndef GRPC_captcha_2eproto__INCLUDED
#define GRPC_captcha_2eproto__INCLUDED

#include "captcha.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace captcha {

// 验证码 gRPC 服务
// 供 ruoyi-cpp (C++) 等后端通过 gRPC 调用，生成并校验行为验证码。
class CaptchaService final {
 public:
  static constexpr char const* service_full_name() {
    return "captcha.CaptchaService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 健康检查 / 版本信息
    virtual ::grpc::Status Ping(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::captcha::PingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::PingResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::PingResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    // 生成滑块验证码（basic 模式：滑块从左侧拖到缺口）
    virtual ::grpc::Status GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::captcha::GetSlideResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetSlideResponse>> AsyncGetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetSlideResponse>>(AsyncGetSlideRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetSlideResponse>> PrepareAsyncGetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetSlideResponse>>(PrepareAsyncGetSlideRaw(context, request, cq));
    }
    // 校验滑块验证码（一次性，校验后 key 失效）
    virtual ::grpc::Status VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::captcha::VerifySlideResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifySlideResponse>> AsyncVerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifySlideResponse>>(AsyncVerifySlideRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifySlideResponse>> PrepareAsyncVerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifySlideResponse>>(PrepareAsyncVerifySlideRaw(context, request, cq));
    }
    // 生成旋转验证码（将圆形图块旋转回正）
    virtual ::grpc::Status GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::captcha::GetRotateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetRotateResponse>> AsyncGetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetRotateResponse>>(AsyncGetRotateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetRotateResponse>> PrepareAsyncGetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetRotateResponse>>(PrepareAsyncGetRotateRaw(context, request, cq));
    }
    // 校验旋转验证码（一次性，校验后 key 失效）
    virtual ::grpc::Status VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::captcha::VerifyRotateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifyRotateResponse>> AsyncVerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifyRotateResponse>>(AsyncVerifyRotateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifyRotateResponse>> PrepareAsyncVerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifyRotateResponse>>(PrepareAsyncVerifyRotateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 健康检查 / 版本信息
      virtual void Ping(::grpc::ClientContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ping(::grpc::ClientContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 生成滑块验证码（basic 模式：滑块从左侧拖到缺口）
      virtual void GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 校验滑块验证码（一次性，校验后 key 失效）
      virtual void VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 生成旋转验证码（将圆形图块旋转回正）
      virtual void GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 校验旋转验证码（一次性，校验后 key 失效）
      virtual void VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::PingResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetSlideResponse>* AsyncGetSlideRaw(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetSlideResponse>* PrepareAsyncGetSlideRaw(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifySlideResponse>* AsyncVerifySlideRaw(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifySlideResponse>* PrepareAsyncVerifySlideRaw(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetRotateResponse>* AsyncGetRotateRaw(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::GetRotateResponse>* PrepareAsyncGetRotateRaw(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifyRotateResponse>* AsyncVerifyRotateRaw(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::captcha::VerifyRotateResponse>* PrepareAsyncVerifyRotateRaw(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Ping(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::captcha::PingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    ::grpc::Status GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::captcha::GetSlideResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>> AsyncGetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>>(AsyncGetSlideRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>> PrepareAsyncGetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>>(PrepareAsyncGetSlideRaw(context, request, cq));
    }
    ::grpc::Status VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::captcha::VerifySlideResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>> AsyncVerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>>(AsyncVerifySlideRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>> PrepareAsyncVerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>>(PrepareAsyncVerifySlideRaw(context, request, cq));
    }
    ::grpc::Status GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::captcha::GetRotateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>> AsyncGetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>>(AsyncGetRotateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>> PrepareAsyncGetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>>(PrepareAsyncGetRotateRaw(context, request, cq));
    }
    ::grpc::Status VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::captcha::VerifyRotateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>> AsyncVerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>>(AsyncVerifyRotateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>> PrepareAsyncVerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>>(PrepareAsyncVerifyRotateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Ping(::grpc::ClientContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response, std::function<void(::grpc::Status)>) override;
      void Ping(::grpc::ClientContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSlide(::grpc::ClientContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response, std::function<void(::grpc::Status)>) override;
      void VerifySlide(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRotate(::grpc::ClientContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response, std::function<void(::grpc::Status)>) override;
      void VerifyRotate(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::PingResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::captcha::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>* AsyncGetSlideRaw(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::GetSlideResponse>* PrepareAsyncGetSlideRaw(::grpc::ClientContext* context, const ::captcha::GetSlideRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>* AsyncVerifySlideRaw(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::VerifySlideResponse>* PrepareAsyncVerifySlideRaw(::grpc::ClientContext* context, const ::captcha::VerifySlideRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>* AsyncGetRotateRaw(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::GetRotateResponse>* PrepareAsyncGetRotateRaw(::grpc::ClientContext* context, const ::captcha::GetRotateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>* AsyncVerifyRotateRaw(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::captcha::VerifyRotateResponse>* PrepareAsyncVerifyRotateRaw(::grpc::ClientContext* context, const ::captcha::VerifyRotateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Ping_;
    const ::grpc::internal::RpcMethod rpcmethod_GetSlide_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifySlide_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRotate_;
    const ::grpc::internal::RpcMethod rpcmethod_VerifyRotate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 健康检查 / 版本信息
    virtual ::grpc::Status Ping(::grpc::ServerContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response);
    // 生成滑块验证码（basic 模式：滑块从左侧拖到缺口）
    virtual ::grpc::Status GetSlide(::grpc::ServerContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response);
    // 校验滑块验证码（一次性，校验后 key 失效）
    virtual ::grpc::Status VerifySlide(::grpc::ServerContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response);
    // 生成旋转验证码（将圆形图块旋转回正）
    virtual ::grpc::Status GetRotate(::grpc::ServerContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response);
    // 校验旋转验证码（一次性，校验后 key 失效）
    virtual ::grpc::Status VerifyRotate(::grpc::ServerContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ping() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::captcha::PingRequest* request, ::grpc::ServerAsyncResponseWriter< ::captcha::PingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSlide() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetSlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSlide(::grpc::ServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSlide(::grpc::ServerContext* context, ::captcha::GetSlideRequest* request, ::grpc::ServerAsyncResponseWriter< ::captcha::GetSlideResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifySlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifySlide() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_VerifySlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifySlide(::grpc::ServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifySlide(::grpc::ServerContext* context, ::captcha::VerifySlideRequest* request, ::grpc::ServerAsyncResponseWriter< ::captcha::VerifySlideResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRotate() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRotate(::grpc::ServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRotate(::grpc::ServerContext* context, ::captcha::GetRotateRequest* request, ::grpc::ServerAsyncResponseWriter< ::captcha::GetRotateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VerifyRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VerifyRotate() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_VerifyRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyRotate(::grpc::ServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyRotate(::grpc::ServerContext* context, ::captcha::VerifyRotateRequest* request, ::grpc::ServerAsyncResponseWriter< ::captcha::VerifyRotateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Ping<WithAsyncMethod_GetSlide<WithAsyncMethod_VerifySlide<WithAsyncMethod_GetRotate<WithAsyncMethod_VerifyRotate<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::captcha::PingRequest, ::captcha::PingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::captcha::PingRequest* request, ::captcha::PingResponse* response) { return this->Ping(context, request, response); }));}
    void SetMessageAllocatorFor_Ping(
        ::grpc::MessageAllocator< ::captcha::PingRequest, ::captcha::PingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::captcha::PingRequest, ::captcha::PingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetSlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSlide() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::captcha::GetSlideRequest, ::captcha::GetSlideResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::captcha::GetSlideRequest* request, ::captcha::GetSlideResponse* response) { return this->GetSlide(context, request, response); }));}
    void SetMessageAllocatorFor_GetSlide(
        ::grpc::MessageAllocator< ::captcha::GetSlideRequest, ::captcha::GetSlideResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::captcha::GetSlideRequest, ::captcha::GetSlideResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSlide(::grpc::ServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSlide(
      ::grpc::CallbackServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VerifySlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifySlide() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::captcha::VerifySlideRequest* request, ::captcha::VerifySlideResponse* response) { return this->VerifySlide(context, request, response); }));}
    void SetMessageAllocatorFor_VerifySlide(
        ::grpc::MessageAllocator< ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifySlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifySlide(::grpc::ServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifySlide(
      ::grpc::CallbackServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRotate() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::captcha::GetRotateRequest, ::captcha::GetRotateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::captcha::GetRotateRequest* request, ::captcha::GetRotateResponse* response) { return this->GetRotate(context, request, response); }));}
    void SetMessageAllocatorFor_GetRotate(
        ::grpc::MessageAllocator< ::captcha::GetRotateRequest, ::captcha::GetRotateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::captcha::GetRotateRequest, ::captcha::GetRotateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRotate(::grpc::ServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRotate(
      ::grpc::CallbackServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_VerifyRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VerifyRotate() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::captcha::VerifyRotateRequest* request, ::captcha::VerifyRotateResponse* response) { return this->VerifyRotate(context, request, response); }));}
    void SetMessageAllocatorFor_VerifyRotate(
        ::grpc::MessageAllocator< ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VerifyRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyRotate(::grpc::ServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyRotate(
      ::grpc::CallbackServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Ping<WithCallbackMethod_GetSlide<WithCallbackMethod_VerifySlide<WithCallbackMethod_GetRotate<WithCallbackMethod_VerifyRotate<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ping() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetSlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSlide() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetSlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSlide(::grpc::ServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifySlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifySlide() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_VerifySlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifySlide(::grpc::ServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRotate() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRotate(::grpc::ServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VerifyRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VerifyRotate() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_VerifyRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyRotate(::grpc::ServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ping() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSlide() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetSlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSlide(::grpc::ServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSlide(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifySlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifySlide() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_VerifySlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifySlide(::grpc::ServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifySlide(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRotate() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRotate(::grpc::ServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRotate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_VerifyRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VerifyRotate() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_VerifyRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyRotate(::grpc::ServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerifyRotate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSlide() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSlide(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSlide(::grpc::ServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSlide(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifySlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifySlide() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifySlide(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifySlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifySlide(::grpc::ServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifySlide(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRotate() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRotate(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRotate(::grpc::ServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRotate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VerifyRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VerifyRotate() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VerifyRotate(context, request, response); }));
    }
    ~WithRawCallbackMethod_VerifyRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VerifyRotate(::grpc::ServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VerifyRotate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ping() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::captcha::PingRequest, ::captcha::PingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::captcha::PingRequest, ::captcha::PingResponse>* streamer) {
                       return this->StreamedPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::captcha::PingRequest* /*request*/, ::captcha::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::captcha::PingRequest,::captcha::PingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSlide() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::captcha::GetSlideRequest, ::captcha::GetSlideResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::captcha::GetSlideRequest, ::captcha::GetSlideResponse>* streamer) {
                       return this->StreamedGetSlide(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSlide(::grpc::ServerContext* /*context*/, const ::captcha::GetSlideRequest* /*request*/, ::captcha::GetSlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSlide(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::captcha::GetSlideRequest,::captcha::GetSlideResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifySlide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifySlide() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::captcha::VerifySlideRequest, ::captcha::VerifySlideResponse>* streamer) {
                       return this->StreamedVerifySlide(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifySlide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifySlide(::grpc::ServerContext* /*context*/, const ::captcha::VerifySlideRequest* /*request*/, ::captcha::VerifySlideResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifySlide(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::captcha::VerifySlideRequest,::captcha::VerifySlideResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRotate() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::captcha::GetRotateRequest, ::captcha::GetRotateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::captcha::GetRotateRequest, ::captcha::GetRotateResponse>* streamer) {
                       return this->StreamedGetRotate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRotate(::grpc::ServerContext* /*context*/, const ::captcha::GetRotateRequest* /*request*/, ::captcha::GetRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRotate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::captcha::GetRotateRequest,::captcha::GetRotateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VerifyRotate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VerifyRotate() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::captcha::VerifyRotateRequest, ::captcha::VerifyRotateResponse>* streamer) {
                       return this->StreamedVerifyRotate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VerifyRotate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VerifyRotate(::grpc::ServerContext* /*context*/, const ::captcha::VerifyRotateRequest* /*request*/, ::captcha::VerifyRotateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerifyRotate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::captcha::VerifyRotateRequest,::captcha::VerifyRotateResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_GetSlide<WithStreamedUnaryMethod_VerifySlide<WithStreamedUnaryMethod_GetRotate<WithStreamedUnaryMethod_VerifyRotate<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_GetSlide<WithStreamedUnaryMethod_VerifySlide<WithStreamedUnaryMethod_GetRotate<WithStreamedUnaryMethod_VerifyRotate<Service > > > > > StreamedService;
};

}  // namespace captcha


#endif  // GRPC_captcha_2eproto__INCLUDED
