// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: captcha.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_captcha_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_captcha_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_captcha_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_captcha_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_captcha_2eproto;
namespace captcha {
class GetRotateRequest;
struct GetRotateRequestDefaultTypeInternal;
extern GetRotateRequestDefaultTypeInternal _GetRotateRequest_default_instance_;
class GetRotateResponse;
struct GetRotateResponseDefaultTypeInternal;
extern GetRotateResponseDefaultTypeInternal _GetRotateResponse_default_instance_;
class GetSlideRequest;
struct GetSlideRequestDefaultTypeInternal;
extern GetSlideRequestDefaultTypeInternal _GetSlideRequest_default_instance_;
class GetSlideResponse;
struct GetSlideResponseDefaultTypeInternal;
extern GetSlideResponseDefaultTypeInternal _GetSlideResponse_default_instance_;
class PingRequest;
struct PingRequestDefaultTypeInternal;
extern PingRequestDefaultTypeInternal _PingRequest_default_instance_;
class PingResponse;
struct PingResponseDefaultTypeInternal;
extern PingResponseDefaultTypeInternal _PingResponse_default_instance_;
class VerifyRotateRequest;
struct VerifyRotateRequestDefaultTypeInternal;
extern VerifyRotateRequestDefaultTypeInternal _VerifyRotateRequest_default_instance_;
class VerifyRotateResponse;
struct VerifyRotateResponseDefaultTypeInternal;
extern VerifyRotateResponseDefaultTypeInternal _VerifyRotateResponse_default_instance_;
class VerifySlideRequest;
struct VerifySlideRequestDefaultTypeInternal;
extern VerifySlideRequestDefaultTypeInternal _VerifySlideRequest_default_instance_;
class VerifySlideResponse;
struct VerifySlideResponseDefaultTypeInternal;
extern VerifySlideResponseDefaultTypeInternal _VerifySlideResponse_default_instance_;
}  // namespace captcha
PROTOBUF_NAMESPACE_OPEN
template<> ::captcha::GetRotateRequest* Arena::CreateMaybeMessage<::captcha::GetRotateRequest>(Arena*);
template<> ::captcha::GetRotateResponse* Arena::CreateMaybeMessage<::captcha::GetRotateResponse>(Arena*);
template<> ::captcha::GetSlideRequest* Arena::CreateMaybeMessage<::captcha::GetSlideRequest>(Arena*);
template<> ::captcha::GetSlideResponse* Arena::CreateMaybeMessage<::captcha::GetSlideResponse>(Arena*);
template<> ::captcha::PingRequest* Arena::CreateMaybeMessage<::captcha::PingRequest>(Arena*);
template<> ::captcha::PingResponse* Arena::CreateMaybeMessage<::captcha::PingResponse>(Arena*);
template<> ::captcha::VerifyRotateRequest* Arena::CreateMaybeMessage<::captcha::VerifyRotateRequest>(Arena*);
template<> ::captcha::VerifyRotateResponse* Arena::CreateMaybeMessage<::captcha::VerifyRotateResponse>(Arena*);
template<> ::captcha::VerifySlideRequest* Arena::CreateMaybeMessage<::captcha::VerifySlideRequest>(Arena*);
template<> ::captcha::VerifySlideResponse* Arena::CreateMaybeMessage<::captcha::VerifySlideResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace captcha {

// ===================================================================

class PingRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:captcha.PingRequest) */ {
 public:
  inline PingRequest() : PingRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR PingRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PingRequest(const PingRequest& from);
  PingRequest(PingRequest&& from) noexcept
    : PingRequest() {
    *this = ::std::move(from);
  }

  inline PingRequest& operator=(const PingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PingRequest& operator=(PingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PingRequest* internal_default_instance() {
    return reinterpret_cast<const PingRequest*>(
               &_PingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PingRequest& a, PingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PingRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PingRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PingRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PingRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PingRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.PingRequest";
  }
  protected:
  explicit PingRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:captcha.PingRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class PingResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.PingResponse) */ {
 public:
  inline PingResponse() : PingResponse(nullptr) {}
  ~PingResponse() override;
  explicit PROTOBUF_CONSTEXPR PingResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PingResponse(const PingResponse& from);
  PingResponse(PingResponse&& from) noexcept
    : PingResponse() {
    *this = ::std::move(from);
  }

  inline PingResponse& operator=(const PingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PingResponse& operator=(PingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PingResponse* internal_default_instance() {
    return reinterpret_cast<const PingResponse*>(
               &_PingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PingResponse& a, PingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PingResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PingResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PingResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PingResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PingResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PingResponse& from) {
    PingResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PingResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.PingResponse";
  }
  protected:
  explicit PingResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 1,
    kUptimeSecFieldNumber = 2,
  };
  // string version = 1;
  void clear_version();
  const std::string& version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // int64 uptime_sec = 2;
  void clear_uptime_sec();
  int64_t uptime_sec() const;
  void set_uptime_sec(int64_t value);
  private:
  int64_t _internal_uptime_sec() const;
  void _internal_set_uptime_sec(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.PingResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
    int64_t uptime_sec_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class GetSlideRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.GetSlideRequest) */ {
 public:
  inline GetSlideRequest() : GetSlideRequest(nullptr) {}
  ~GetSlideRequest() override;
  explicit PROTOBUF_CONSTEXPR GetSlideRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetSlideRequest(const GetSlideRequest& from);
  GetSlideRequest(GetSlideRequest&& from) noexcept
    : GetSlideRequest() {
    *this = ::std::move(from);
  }

  inline GetSlideRequest& operator=(const GetSlideRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetSlideRequest& operator=(GetSlideRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetSlideRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetSlideRequest* internal_default_instance() {
    return reinterpret_cast<const GetSlideRequest*>(
               &_GetSlideRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetSlideRequest& a, GetSlideRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetSlideRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetSlideRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetSlideRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetSlideRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetSlideRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetSlideRequest& from) {
    GetSlideRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetSlideRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.GetSlideRequest";
  }
  protected:
  explicit GetSlideRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
  };
  // int32 width = 1;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 2;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.GetSlideRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t width_;
    int32_t height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class GetSlideResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.GetSlideResponse) */ {
 public:
  inline GetSlideResponse() : GetSlideResponse(nullptr) {}
  ~GetSlideResponse() override;
  explicit PROTOBUF_CONSTEXPR GetSlideResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetSlideResponse(const GetSlideResponse& from);
  GetSlideResponse(GetSlideResponse&& from) noexcept
    : GetSlideResponse() {
    *this = ::std::move(from);
  }

  inline GetSlideResponse& operator=(const GetSlideResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetSlideResponse& operator=(GetSlideResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetSlideResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetSlideResponse* internal_default_instance() {
    return reinterpret_cast<const GetSlideResponse*>(
               &_GetSlideResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetSlideResponse& a, GetSlideResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetSlideResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetSlideResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetSlideResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetSlideResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetSlideResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetSlideResponse& from) {
    GetSlideResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetSlideResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.GetSlideResponse";
  }
  protected:
  explicit GetSlideResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kMasterImageFieldNumber = 2,
    kTileImageFieldNumber = 3,
    kTileXFieldNumber = 4,
    kTileYFieldNumber = 5,
    kTileWidthFieldNumber = 6,
    kTileHeightFieldNumber = 7,
    kMasterWidthFieldNumber = 8,
    kMasterHeightFieldNumber = 9,
    kDevAnswerXFieldNumber = 10,
    kDevAnswerYFieldNumber = 11,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // string master_image = 2;
  void clear_master_image();
  const std::string& master_image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_master_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_master_image();
  PROTOBUF_NODISCARD std::string* release_master_image();
  void set_allocated_master_image(std::string* master_image);
  private:
  const std::string& _internal_master_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_master_image(const std::string& value);
  std::string* _internal_mutable_master_image();
  public:

  // string tile_image = 3;
  void clear_tile_image();
  const std::string& tile_image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tile_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tile_image();
  PROTOBUF_NODISCARD std::string* release_tile_image();
  void set_allocated_tile_image(std::string* tile_image);
  private:
  const std::string& _internal_tile_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tile_image(const std::string& value);
  std::string* _internal_mutable_tile_image();
  public:

  // int32 tile_x = 4;
  void clear_tile_x();
  int32_t tile_x() const;
  void set_tile_x(int32_t value);
  private:
  int32_t _internal_tile_x() const;
  void _internal_set_tile_x(int32_t value);
  public:

  // int32 tile_y = 5;
  void clear_tile_y();
  int32_t tile_y() const;
  void set_tile_y(int32_t value);
  private:
  int32_t _internal_tile_y() const;
  void _internal_set_tile_y(int32_t value);
  public:

  // int32 tile_width = 6;
  void clear_tile_width();
  int32_t tile_width() const;
  void set_tile_width(int32_t value);
  private:
  int32_t _internal_tile_width() const;
  void _internal_set_tile_width(int32_t value);
  public:

  // int32 tile_height = 7;
  void clear_tile_height();
  int32_t tile_height() const;
  void set_tile_height(int32_t value);
  private:
  int32_t _internal_tile_height() const;
  void _internal_set_tile_height(int32_t value);
  public:

  // int32 master_width = 8;
  void clear_master_width();
  int32_t master_width() const;
  void set_master_width(int32_t value);
  private:
  int32_t _internal_master_width() const;
  void _internal_set_master_width(int32_t value);
  public:

  // int32 master_height = 9;
  void clear_master_height();
  int32_t master_height() const;
  void set_master_height(int32_t value);
  private:
  int32_t _internal_master_height() const;
  void _internal_set_master_height(int32_t value);
  public:

  // int32 dev_answer_x = 10;
  void clear_dev_answer_x();
  int32_t dev_answer_x() const;
  void set_dev_answer_x(int32_t value);
  private:
  int32_t _internal_dev_answer_x() const;
  void _internal_set_dev_answer_x(int32_t value);
  public:

  // int32 dev_answer_y = 11;
  void clear_dev_answer_y();
  int32_t dev_answer_y() const;
  void set_dev_answer_y(int32_t value);
  private:
  int32_t _internal_dev_answer_y() const;
  void _internal_set_dev_answer_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.GetSlideResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr master_image_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tile_image_;
    int32_t tile_x_;
    int32_t tile_y_;
    int32_t tile_width_;
    int32_t tile_height_;
    int32_t master_width_;
    int32_t master_height_;
    int32_t dev_answer_x_;
    int32_t dev_answer_y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class VerifySlideRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.VerifySlideRequest) */ {
 public:
  inline VerifySlideRequest() : VerifySlideRequest(nullptr) {}
  ~VerifySlideRequest() override;
  explicit PROTOBUF_CONSTEXPR VerifySlideRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifySlideRequest(const VerifySlideRequest& from);
  VerifySlideRequest(VerifySlideRequest&& from) noexcept
    : VerifySlideRequest() {
    *this = ::std::move(from);
  }

  inline VerifySlideRequest& operator=(const VerifySlideRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifySlideRequest& operator=(VerifySlideRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifySlideRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifySlideRequest* internal_default_instance() {
    return reinterpret_cast<const VerifySlideRequest*>(
               &_VerifySlideRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(VerifySlideRequest& a, VerifySlideRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifySlideRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifySlideRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifySlideRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifySlideRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifySlideRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifySlideRequest& from) {
    VerifySlideRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifySlideRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.VerifySlideRequest";
  }
  protected:
  explicit VerifySlideRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // int32 x = 2;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 3;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.VerifySlideRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    int32_t x_;
    int32_t y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class VerifySlideResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.VerifySlideResponse) */ {
 public:
  inline VerifySlideResponse() : VerifySlideResponse(nullptr) {}
  ~VerifySlideResponse() override;
  explicit PROTOBUF_CONSTEXPR VerifySlideResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifySlideResponse(const VerifySlideResponse& from);
  VerifySlideResponse(VerifySlideResponse&& from) noexcept
    : VerifySlideResponse() {
    *this = ::std::move(from);
  }

  inline VerifySlideResponse& operator=(const VerifySlideResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifySlideResponse& operator=(VerifySlideResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifySlideResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifySlideResponse* internal_default_instance() {
    return reinterpret_cast<const VerifySlideResponse*>(
               &_VerifySlideResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(VerifySlideResponse& a, VerifySlideResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifySlideResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifySlideResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifySlideResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifySlideResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifySlideResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifySlideResponse& from) {
    VerifySlideResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifySlideResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.VerifySlideResponse";
  }
  protected:
  explicit VerifySlideResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // bool result = 1;
  void clear_result();
  bool result() const;
  void set_result(bool value);
  private:
  bool _internal_result() const;
  void _internal_set_result(bool value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.VerifySlideResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class GetRotateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.GetRotateRequest) */ {
 public:
  inline GetRotateRequest() : GetRotateRequest(nullptr) {}
  ~GetRotateRequest() override;
  explicit PROTOBUF_CONSTEXPR GetRotateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetRotateRequest(const GetRotateRequest& from);
  GetRotateRequest(GetRotateRequest&& from) noexcept
    : GetRotateRequest() {
    *this = ::std::move(from);
  }

  inline GetRotateRequest& operator=(const GetRotateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetRotateRequest& operator=(GetRotateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetRotateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetRotateRequest* internal_default_instance() {
    return reinterpret_cast<const GetRotateRequest*>(
               &_GetRotateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetRotateRequest& a, GetRotateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetRotateRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetRotateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetRotateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetRotateRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetRotateRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetRotateRequest& from) {
    GetRotateRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetRotateRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.GetRotateRequest";
  }
  protected:
  explicit GetRotateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSizeFieldNumber = 1,
  };
  // int32 size = 1;
  void clear_size();
  int32_t size() const;
  void set_size(int32_t value);
  private:
  int32_t _internal_size() const;
  void _internal_set_size(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.GetRotateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class GetRotateResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.GetRotateResponse) */ {
 public:
  inline GetRotateResponse() : GetRotateResponse(nullptr) {}
  ~GetRotateResponse() override;
  explicit PROTOBUF_CONSTEXPR GetRotateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetRotateResponse(const GetRotateResponse& from);
  GetRotateResponse(GetRotateResponse&& from) noexcept
    : GetRotateResponse() {
    *this = ::std::move(from);
  }

  inline GetRotateResponse& operator=(const GetRotateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetRotateResponse& operator=(GetRotateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetRotateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetRotateResponse* internal_default_instance() {
    return reinterpret_cast<const GetRotateResponse*>(
               &_GetRotateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GetRotateResponse& a, GetRotateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetRotateResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetRotateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetRotateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetRotateResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetRotateResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetRotateResponse& from) {
    GetRotateResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetRotateResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.GetRotateResponse";
  }
  protected:
  explicit GetRotateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kMasterImageFieldNumber = 2,
    kThumbImageFieldNumber = 3,
    kDevAngleFieldNumber = 4,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // string master_image = 2;
  void clear_master_image();
  const std::string& master_image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_master_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_master_image();
  PROTOBUF_NODISCARD std::string* release_master_image();
  void set_allocated_master_image(std::string* master_image);
  private:
  const std::string& _internal_master_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_master_image(const std::string& value);
  std::string* _internal_mutable_master_image();
  public:

  // string thumb_image = 3;
  void clear_thumb_image();
  const std::string& thumb_image() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_thumb_image(ArgT0&& arg0, ArgT... args);
  std::string* mutable_thumb_image();
  PROTOBUF_NODISCARD std::string* release_thumb_image();
  void set_allocated_thumb_image(std::string* thumb_image);
  private:
  const std::string& _internal_thumb_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_thumb_image(const std::string& value);
  std::string* _internal_mutable_thumb_image();
  public:

  // int32 dev_angle = 4;
  void clear_dev_angle();
  int32_t dev_angle() const;
  void set_dev_angle(int32_t value);
  private:
  int32_t _internal_dev_angle() const;
  void _internal_set_dev_angle(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.GetRotateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr master_image_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr thumb_image_;
    int32_t dev_angle_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class VerifyRotateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.VerifyRotateRequest) */ {
 public:
  inline VerifyRotateRequest() : VerifyRotateRequest(nullptr) {}
  ~VerifyRotateRequest() override;
  explicit PROTOBUF_CONSTEXPR VerifyRotateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifyRotateRequest(const VerifyRotateRequest& from);
  VerifyRotateRequest(VerifyRotateRequest&& from) noexcept
    : VerifyRotateRequest() {
    *this = ::std::move(from);
  }

  inline VerifyRotateRequest& operator=(const VerifyRotateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyRotateRequest& operator=(VerifyRotateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyRotateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyRotateRequest* internal_default_instance() {
    return reinterpret_cast<const VerifyRotateRequest*>(
               &_VerifyRotateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(VerifyRotateRequest& a, VerifyRotateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifyRotateRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyRotateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyRotateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifyRotateRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifyRotateRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifyRotateRequest& from) {
    VerifyRotateRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifyRotateRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.VerifyRotateRequest";
  }
  protected:
  explicit VerifyRotateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kAngleFieldNumber = 2,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // int32 angle = 2;
  void clear_angle();
  int32_t angle() const;
  void set_angle(int32_t value);
  private:
  int32_t _internal_angle() const;
  void _internal_set_angle(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.VerifyRotateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    int32_t angle_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// -------------------------------------------------------------------

class VerifyRotateResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:captcha.VerifyRotateResponse) */ {
 public:
  inline VerifyRotateResponse() : VerifyRotateResponse(nullptr) {}
  ~VerifyRotateResponse() override;
  explicit PROTOBUF_CONSTEXPR VerifyRotateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifyRotateResponse(const VerifyRotateResponse& from);
  VerifyRotateResponse(VerifyRotateResponse&& from) noexcept
    : VerifyRotateResponse() {
    *this = ::std::move(from);
  }

  inline VerifyRotateResponse& operator=(const VerifyRotateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyRotateResponse& operator=(VerifyRotateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyRotateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyRotateResponse* internal_default_instance() {
    return reinterpret_cast<const VerifyRotateResponse*>(
               &_VerifyRotateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(VerifyRotateResponse& a, VerifyRotateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifyRotateResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyRotateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyRotateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifyRotateResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifyRotateResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifyRotateResponse& from) {
    VerifyRotateResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifyRotateResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "captcha.VerifyRotateResponse";
  }
  protected:
  explicit VerifyRotateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // bool result = 1;
  void clear_result();
  bool result() const;
  void set_result(bool value);
  private:
  bool _internal_result() const;
  void _internal_set_result(bool value);
  public:

  // @@protoc_insertion_point(class_scope:captcha.VerifyRotateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_captcha_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PingRequest

// -------------------------------------------------------------------

// PingResponse

// string version = 1;
inline void PingResponse::clear_version() {
  _impl_.version_.ClearToEmpty();
}
inline const std::string& PingResponse::version() const {
  // @@protoc_insertion_point(field_get:captcha.PingResponse.version)
  return _internal_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PingResponse::set_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.PingResponse.version)
}
inline std::string* PingResponse::mutable_version() {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:captcha.PingResponse.version)
  return _s;
}
inline const std::string& PingResponse::_internal_version() const {
  return _impl_.version_.Get();
}
inline void PingResponse::_internal_set_version(const std::string& value) {
  
  _impl_.version_.Set(value, GetArenaForAllocation());
}
inline std::string* PingResponse::_internal_mutable_version() {
  
  return _impl_.version_.Mutable(GetArenaForAllocation());
}
inline std::string* PingResponse::release_version() {
  // @@protoc_insertion_point(field_release:captcha.PingResponse.version)
  return _impl_.version_.Release();
}
inline void PingResponse::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  _impl_.version_.SetAllocated(version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.version_.IsDefault()) {
    _impl_.version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.PingResponse.version)
}

// int64 uptime_sec = 2;
inline void PingResponse::clear_uptime_sec() {
  _impl_.uptime_sec_ = int64_t{0};
}
inline int64_t PingResponse::_internal_uptime_sec() const {
  return _impl_.uptime_sec_;
}
inline int64_t PingResponse::uptime_sec() const {
  // @@protoc_insertion_point(field_get:captcha.PingResponse.uptime_sec)
  return _internal_uptime_sec();
}
inline void PingResponse::_internal_set_uptime_sec(int64_t value) {
  
  _impl_.uptime_sec_ = value;
}
inline void PingResponse::set_uptime_sec(int64_t value) {
  _internal_set_uptime_sec(value);
  // @@protoc_insertion_point(field_set:captcha.PingResponse.uptime_sec)
}

// -------------------------------------------------------------------

// GetSlideRequest

// int32 width = 1;
inline void GetSlideRequest::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t GetSlideRequest::_internal_width() const {
  return _impl_.width_;
}
inline int32_t GetSlideRequest::width() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideRequest.width)
  return _internal_width();
}
inline void GetSlideRequest::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void GetSlideRequest::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideRequest.width)
}

// int32 height = 2;
inline void GetSlideRequest::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t GetSlideRequest::_internal_height() const {
  return _impl_.height_;
}
inline int32_t GetSlideRequest::height() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideRequest.height)
  return _internal_height();
}
inline void GetSlideRequest::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void GetSlideRequest::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideRequest.height)
}

// -------------------------------------------------------------------

// GetSlideResponse

// string key = 1;
inline void GetSlideResponse::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& GetSlideResponse::key() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetSlideResponse::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.key)
}
inline std::string* GetSlideResponse::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:captcha.GetSlideResponse.key)
  return _s;
}
inline const std::string& GetSlideResponse::_internal_key() const {
  return _impl_.key_.Get();
}
inline void GetSlideResponse::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* GetSlideResponse::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* GetSlideResponse::release_key() {
  // @@protoc_insertion_point(field_release:captcha.GetSlideResponse.key)
  return _impl_.key_.Release();
}
inline void GetSlideResponse::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.GetSlideResponse.key)
}

// string master_image = 2;
inline void GetSlideResponse::clear_master_image() {
  _impl_.master_image_.ClearToEmpty();
}
inline const std::string& GetSlideResponse::master_image() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.master_image)
  return _internal_master_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetSlideResponse::set_master_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.master_image_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.master_image)
}
inline std::string* GetSlideResponse::mutable_master_image() {
  std::string* _s = _internal_mutable_master_image();
  // @@protoc_insertion_point(field_mutable:captcha.GetSlideResponse.master_image)
  return _s;
}
inline const std::string& GetSlideResponse::_internal_master_image() const {
  return _impl_.master_image_.Get();
}
inline void GetSlideResponse::_internal_set_master_image(const std::string& value) {
  
  _impl_.master_image_.Set(value, GetArenaForAllocation());
}
inline std::string* GetSlideResponse::_internal_mutable_master_image() {
  
  return _impl_.master_image_.Mutable(GetArenaForAllocation());
}
inline std::string* GetSlideResponse::release_master_image() {
  // @@protoc_insertion_point(field_release:captcha.GetSlideResponse.master_image)
  return _impl_.master_image_.Release();
}
inline void GetSlideResponse::set_allocated_master_image(std::string* master_image) {
  if (master_image != nullptr) {
    
  } else {
    
  }
  _impl_.master_image_.SetAllocated(master_image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.master_image_.IsDefault()) {
    _impl_.master_image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.GetSlideResponse.master_image)
}

// string tile_image = 3;
inline void GetSlideResponse::clear_tile_image() {
  _impl_.tile_image_.ClearToEmpty();
}
inline const std::string& GetSlideResponse::tile_image() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.tile_image)
  return _internal_tile_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetSlideResponse::set_tile_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tile_image_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.tile_image)
}
inline std::string* GetSlideResponse::mutable_tile_image() {
  std::string* _s = _internal_mutable_tile_image();
  // @@protoc_insertion_point(field_mutable:captcha.GetSlideResponse.tile_image)
  return _s;
}
inline const std::string& GetSlideResponse::_internal_tile_image() const {
  return _impl_.tile_image_.Get();
}
inline void GetSlideResponse::_internal_set_tile_image(const std::string& value) {
  
  _impl_.tile_image_.Set(value, GetArenaForAllocation());
}
inline std::string* GetSlideResponse::_internal_mutable_tile_image() {
  
  return _impl_.tile_image_.Mutable(GetArenaForAllocation());
}
inline std::string* GetSlideResponse::release_tile_image() {
  // @@protoc_insertion_point(field_release:captcha.GetSlideResponse.tile_image)
  return _impl_.tile_image_.Release();
}
inline void GetSlideResponse::set_allocated_tile_image(std::string* tile_image) {
  if (tile_image != nullptr) {
    
  } else {
    
  }
  _impl_.tile_image_.SetAllocated(tile_image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tile_image_.IsDefault()) {
    _impl_.tile_image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.GetSlideResponse.tile_image)
}

// int32 tile_x = 4;
inline void GetSlideResponse::clear_tile_x() {
  _impl_.tile_x_ = 0;
}
inline int32_t GetSlideResponse::_internal_tile_x() const {
  return _impl_.tile_x_;
}
inline int32_t GetSlideResponse::tile_x() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.tile_x)
  return _internal_tile_x();
}
inline void GetSlideResponse::_internal_set_tile_x(int32_t value) {
  
  _impl_.tile_x_ = value;
}
inline void GetSlideResponse::set_tile_x(int32_t value) {
  _internal_set_tile_x(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.tile_x)
}

// int32 tile_y = 5;
inline void GetSlideResponse::clear_tile_y() {
  _impl_.tile_y_ = 0;
}
inline int32_t GetSlideResponse::_internal_tile_y() const {
  return _impl_.tile_y_;
}
inline int32_t GetSlideResponse::tile_y() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.tile_y)
  return _internal_tile_y();
}
inline void GetSlideResponse::_internal_set_tile_y(int32_t value) {
  
  _impl_.tile_y_ = value;
}
inline void GetSlideResponse::set_tile_y(int32_t value) {
  _internal_set_tile_y(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.tile_y)
}

// int32 tile_width = 6;
inline void GetSlideResponse::clear_tile_width() {
  _impl_.tile_width_ = 0;
}
inline int32_t GetSlideResponse::_internal_tile_width() const {
  return _impl_.tile_width_;
}
inline int32_t GetSlideResponse::tile_width() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.tile_width)
  return _internal_tile_width();
}
inline void GetSlideResponse::_internal_set_tile_width(int32_t value) {
  
  _impl_.tile_width_ = value;
}
inline void GetSlideResponse::set_tile_width(int32_t value) {
  _internal_set_tile_width(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.tile_width)
}

// int32 tile_height = 7;
inline void GetSlideResponse::clear_tile_height() {
  _impl_.tile_height_ = 0;
}
inline int32_t GetSlideResponse::_internal_tile_height() const {
  return _impl_.tile_height_;
}
inline int32_t GetSlideResponse::tile_height() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.tile_height)
  return _internal_tile_height();
}
inline void GetSlideResponse::_internal_set_tile_height(int32_t value) {
  
  _impl_.tile_height_ = value;
}
inline void GetSlideResponse::set_tile_height(int32_t value) {
  _internal_set_tile_height(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.tile_height)
}

// int32 master_width = 8;
inline void GetSlideResponse::clear_master_width() {
  _impl_.master_width_ = 0;
}
inline int32_t GetSlideResponse::_internal_master_width() const {
  return _impl_.master_width_;
}
inline int32_t GetSlideResponse::master_width() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.master_width)
  return _internal_master_width();
}
inline void GetSlideResponse::_internal_set_master_width(int32_t value) {
  
  _impl_.master_width_ = value;
}
inline void GetSlideResponse::set_master_width(int32_t value) {
  _internal_set_master_width(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.master_width)
}

// int32 master_height = 9;
inline void GetSlideResponse::clear_master_height() {
  _impl_.master_height_ = 0;
}
inline int32_t GetSlideResponse::_internal_master_height() const {
  return _impl_.master_height_;
}
inline int32_t GetSlideResponse::master_height() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.master_height)
  return _internal_master_height();
}
inline void GetSlideResponse::_internal_set_master_height(int32_t value) {
  
  _impl_.master_height_ = value;
}
inline void GetSlideResponse::set_master_height(int32_t value) {
  _internal_set_master_height(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.master_height)
}

// int32 dev_answer_x = 10;
inline void GetSlideResponse::clear_dev_answer_x() {
  _impl_.dev_answer_x_ = 0;
}
inline int32_t GetSlideResponse::_internal_dev_answer_x() const {
  return _impl_.dev_answer_x_;
}
inline int32_t GetSlideResponse::dev_answer_x() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.dev_answer_x)
  return _internal_dev_answer_x();
}
inline void GetSlideResponse::_internal_set_dev_answer_x(int32_t value) {
  
  _impl_.dev_answer_x_ = value;
}
inline void GetSlideResponse::set_dev_answer_x(int32_t value) {
  _internal_set_dev_answer_x(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.dev_answer_x)
}

// int32 dev_answer_y = 11;
inline void GetSlideResponse::clear_dev_answer_y() {
  _impl_.dev_answer_y_ = 0;
}
inline int32_t GetSlideResponse::_internal_dev_answer_y() const {
  return _impl_.dev_answer_y_;
}
inline int32_t GetSlideResponse::dev_answer_y() const {
  // @@protoc_insertion_point(field_get:captcha.GetSlideResponse.dev_answer_y)
  return _internal_dev_answer_y();
}
inline void GetSlideResponse::_internal_set_dev_answer_y(int32_t value) {
  
  _impl_.dev_answer_y_ = value;
}
inline void GetSlideResponse::set_dev_answer_y(int32_t value) {
  _internal_set_dev_answer_y(value);
  // @@protoc_insertion_point(field_set:captcha.GetSlideResponse.dev_answer_y)
}

// -------------------------------------------------------------------

// VerifySlideRequest

// string key = 1;
inline void VerifySlideRequest::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& VerifySlideRequest::key() const {
  // @@protoc_insertion_point(field_get:captcha.VerifySlideRequest.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifySlideRequest::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.VerifySlideRequest.key)
}
inline std::string* VerifySlideRequest::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:captcha.VerifySlideRequest.key)
  return _s;
}
inline const std::string& VerifySlideRequest::_internal_key() const {
  return _impl_.key_.Get();
}
inline void VerifySlideRequest::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifySlideRequest::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifySlideRequest::release_key() {
  // @@protoc_insertion_point(field_release:captcha.VerifySlideRequest.key)
  return _impl_.key_.Release();
}
inline void VerifySlideRequest::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.VerifySlideRequest.key)
}

// int32 x = 2;
inline void VerifySlideRequest::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t VerifySlideRequest::_internal_x() const {
  return _impl_.x_;
}
inline int32_t VerifySlideRequest::x() const {
  // @@protoc_insertion_point(field_get:captcha.VerifySlideRequest.x)
  return _internal_x();
}
inline void VerifySlideRequest::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void VerifySlideRequest::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:captcha.VerifySlideRequest.x)
}

// int32 y = 3;
inline void VerifySlideRequest::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t VerifySlideRequest::_internal_y() const {
  return _impl_.y_;
}
inline int32_t VerifySlideRequest::y() const {
  // @@protoc_insertion_point(field_get:captcha.VerifySlideRequest.y)
  return _internal_y();
}
inline void VerifySlideRequest::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void VerifySlideRequest::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:captcha.VerifySlideRequest.y)
}

// -------------------------------------------------------------------

// VerifySlideResponse

// bool result = 1;
inline void VerifySlideResponse::clear_result() {
  _impl_.result_ = false;
}
inline bool VerifySlideResponse::_internal_result() const {
  return _impl_.result_;
}
inline bool VerifySlideResponse::result() const {
  // @@protoc_insertion_point(field_get:captcha.VerifySlideResponse.result)
  return _internal_result();
}
inline void VerifySlideResponse::_internal_set_result(bool value) {
  
  _impl_.result_ = value;
}
inline void VerifySlideResponse::set_result(bool value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:captcha.VerifySlideResponse.result)
}

// -------------------------------------------------------------------

// GetRotateRequest

// int32 size = 1;
inline void GetRotateRequest::clear_size() {
  _impl_.size_ = 0;
}
inline int32_t GetRotateRequest::_internal_size() const {
  return _impl_.size_;
}
inline int32_t GetRotateRequest::size() const {
  // @@protoc_insertion_point(field_get:captcha.GetRotateRequest.size)
  return _internal_size();
}
inline void GetRotateRequest::_internal_set_size(int32_t value) {
  
  _impl_.size_ = value;
}
inline void GetRotateRequest::set_size(int32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:captcha.GetRotateRequest.size)
}

// -------------------------------------------------------------------

// GetRotateResponse

// string key = 1;
inline void GetRotateResponse::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& GetRotateResponse::key() const {
  // @@protoc_insertion_point(field_get:captcha.GetRotateResponse.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetRotateResponse::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.GetRotateResponse.key)
}
inline std::string* GetRotateResponse::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:captcha.GetRotateResponse.key)
  return _s;
}
inline const std::string& GetRotateResponse::_internal_key() const {
  return _impl_.key_.Get();
}
inline void GetRotateResponse::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* GetRotateResponse::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* GetRotateResponse::release_key() {
  // @@protoc_insertion_point(field_release:captcha.GetRotateResponse.key)
  return _impl_.key_.Release();
}
inline void GetRotateResponse::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.GetRotateResponse.key)
}

// string master_image = 2;
inline void GetRotateResponse::clear_master_image() {
  _impl_.master_image_.ClearToEmpty();
}
inline const std::string& GetRotateResponse::master_image() const {
  // @@protoc_insertion_point(field_get:captcha.GetRotateResponse.master_image)
  return _internal_master_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetRotateResponse::set_master_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.master_image_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.GetRotateResponse.master_image)
}
inline std::string* GetRotateResponse::mutable_master_image() {
  std::string* _s = _internal_mutable_master_image();
  // @@protoc_insertion_point(field_mutable:captcha.GetRotateResponse.master_image)
  return _s;
}
inline const std::string& GetRotateResponse::_internal_master_image() const {
  return _impl_.master_image_.Get();
}
inline void GetRotateResponse::_internal_set_master_image(const std::string& value) {
  
  _impl_.master_image_.Set(value, GetArenaForAllocation());
}
inline std::string* GetRotateResponse::_internal_mutable_master_image() {
  
  return _impl_.master_image_.Mutable(GetArenaForAllocation());
}
inline std::string* GetRotateResponse::release_master_image() {
  // @@protoc_insertion_point(field_release:captcha.GetRotateResponse.master_image)
  return _impl_.master_image_.Release();
}
inline void GetRotateResponse::set_allocated_master_image(std::string* master_image) {
  if (master_image != nullptr) {
    
  } else {
    
  }
  _impl_.master_image_.SetAllocated(master_image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.master_image_.IsDefault()) {
    _impl_.master_image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.GetRotateResponse.master_image)
}

// string thumb_image = 3;
inline void GetRotateResponse::clear_thumb_image() {
  _impl_.thumb_image_.ClearToEmpty();
}
inline const std::string& GetRotateResponse::thumb_image() const {
  // @@protoc_insertion_point(field_get:captcha.GetRotateResponse.thumb_image)
  return _internal_thumb_image();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetRotateResponse::set_thumb_image(ArgT0&& arg0, ArgT... args) {
 
 _impl_.thumb_image_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.GetRotateResponse.thumb_image)
}
inline std::string* GetRotateResponse::mutable_thumb_image() {
  std::string* _s = _internal_mutable_thumb_image();
  // @@protoc_insertion_point(field_mutable:captcha.GetRotateResponse.thumb_image)
  return _s;
}
inline const std::string& GetRotateResponse::_internal_thumb_image() const {
  return _impl_.thumb_image_.Get();
}
inline void GetRotateResponse::_internal_set_thumb_image(const std::string& value) {
  
  _impl_.thumb_image_.Set(value, GetArenaForAllocation());
}
inline std::string* GetRotateResponse::_internal_mutable_thumb_image() {
  
  return _impl_.thumb_image_.Mutable(GetArenaForAllocation());
}
inline std::string* GetRotateResponse::release_thumb_image() {
  // @@protoc_insertion_point(field_release:captcha.GetRotateResponse.thumb_image)
  return _impl_.thumb_image_.Release();
}
inline void GetRotateResponse::set_allocated_thumb_image(std::string* thumb_image) {
  if (thumb_image != nullptr) {
    
  } else {
    
  }
  _impl_.thumb_image_.SetAllocated(thumb_image, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.thumb_image_.IsDefault()) {
    _impl_.thumb_image_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.GetRotateResponse.thumb_image)
}

// int32 dev_angle = 4;
inline void GetRotateResponse::clear_dev_angle() {
  _impl_.dev_angle_ = 0;
}
inline int32_t GetRotateResponse::_internal_dev_angle() const {
  return _impl_.dev_angle_;
}
inline int32_t GetRotateResponse::dev_angle() const {
  // @@protoc_insertion_point(field_get:captcha.GetRotateResponse.dev_angle)
  return _internal_dev_angle();
}
inline void GetRotateResponse::_internal_set_dev_angle(int32_t value) {
  
  _impl_.dev_angle_ = value;
}
inline void GetRotateResponse::set_dev_angle(int32_t value) {
  _internal_set_dev_angle(value);
  // @@protoc_insertion_point(field_set:captcha.GetRotateResponse.dev_angle)
}

// -------------------------------------------------------------------

// VerifyRotateRequest

// string key = 1;
inline void VerifyRotateRequest::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& VerifyRotateRequest::key() const {
  // @@protoc_insertion_point(field_get:captcha.VerifyRotateRequest.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifyRotateRequest::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:captcha.VerifyRotateRequest.key)
}
inline std::string* VerifyRotateRequest::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:captcha.VerifyRotateRequest.key)
  return _s;
}
inline const std::string& VerifyRotateRequest::_internal_key() const {
  return _impl_.key_.Get();
}
inline void VerifyRotateRequest::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifyRotateRequest::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifyRotateRequest::release_key() {
  // @@protoc_insertion_point(field_release:captcha.VerifyRotateRequest.key)
  return _impl_.key_.Release();
}
inline void VerifyRotateRequest::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:captcha.VerifyRotateRequest.key)
}

// int32 angle = 2;
inline void VerifyRotateRequest::clear_angle() {
  _impl_.angle_ = 0;
}
inline int32_t VerifyRotateRequest::_internal_angle() const {
  return _impl_.angle_;
}
inline int32_t VerifyRotateRequest::angle() const {
  // @@protoc_insertion_point(field_get:captcha.VerifyRotateRequest.angle)
  return _internal_angle();
}
inline void VerifyRotateRequest::_internal_set_angle(int32_t value) {
  
  _impl_.angle_ = value;
}
inline void VerifyRotateRequest::set_angle(int32_t value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:captcha.VerifyRotateRequest.angle)
}

// -------------------------------------------------------------------

// VerifyRotateResponse

// bool result = 1;
inline void VerifyRotateResponse::clear_result() {
  _impl_.result_ = false;
}
inline bool VerifyRotateResponse::_internal_result() const {
  return _impl_.result_;
}
inline bool VerifyRotateResponse::result() const {
  // @@protoc_insertion_point(field_get:captcha.VerifyRotateResponse.result)
  return _internal_result();
}
inline void VerifyRotateResponse::_internal_set_result(bool value) {
  
  _impl_.result_ = value;
}
inline void VerifyRotateResponse::set_result(bool value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:captcha.VerifyRotateResponse.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace captcha

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_captcha_2eproto
